### PR TITLE
replaced all new Buffer(...) by Buffer.alloc(...) and Buffer.from(...)

### PR DESCRIPTION
**Pull request by Reg011**
Replaced Node depreciations since Node v10

### CODE REVIEW

**Comment by diegomura** [comment]
Looks good! I'm not familiarized with this Buffer api. Did you check that everything runs well?

**Comment by Reg011** [comment]
You can read about it like I did here: https://nodejs.org/api/buffer.html. It's simple really, we just have to replace `new Buffer` with the right stuff (Buffer.from or Buffer.alloc). However I'm not exactly familiar with either `fontkit`, `pdfkit` and `png-js`. Is there a test-suite setup I could run like jest or anything else ?

**Comment by Reg011** [comment]
`Buffer.alloc` when a number is passed, `Buffer.from` for everything else (`string`, `array`, `buffer` or `object`).

**Comment by Reg011** [comment]
@diegomura I'm afraid that since you've added some Linux exclusive dependencies in your `npm`. I cannot either `npm install` or `mocha` the project since I'm on Windows. You will have to test this pull request on your own to ensure that it's working correctly. Same for those two other pull requests: 

* https://github.com/react-pdf/pdfkit/pull/9
* https://github.com/react-pdf/png.js/pull/2

**Comment by mrlubos** [comment]
Hi @Reg011 @diegomura, any updates on this pull request? Thanks!

**Comment by Sickora-Kate-PFG** [comment]
Any update as to when this might be merged? Running into this when calling renderToStream.

**Comment by mrlubos** [comment]
@Sickora-Kate-PFG Seems this fork is dead, the original repository is more active. Although this particular fix hasn't been merged there either...

**Comment by diegomura** [comment]
Just catching up sorry. This seems good to me!

**Pull request merged**
